### ISSUE TITLE
install fail:Magick++ not found

### ISSUE THREAD

**Issue by gueat** [hhatto/pgmagick#59]
ERROR: Command errored out with exit status 1:
     command: 'e:\tool\env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-5xrphzu3\\pgmagick\\setup.py'"'"'; __file__='"'
"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-5xrphzu3\\pgmagick\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();e
xec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-5xrphzu3\pgmagick\pip-egg-info'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-5xrphzu3\pgmagick\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-5xrphzu3\pgmagick\setup.py", line 128, in <module>
        raise Exception("Magick++ not found")
    Exception: Magick++ not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by komackaj** [comment]
Installing using `pip` on Windows is not officially maintained - see [docs](https://github.com/hhatto/pgmagick#windows). It probably fails due to [missing install prerequisites](https://github.com/hhatto/pgmagick#requirements) - specifically GraphicsMagick C++ development files.

Could you try/use Wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pgmagick ?

**Comment by hhatto** [comment]
No reply for a long time, so I will close it once.
If you are still experiencing the same problem, please open it again.
